// Generated by the OpenNext Cloudflare build step.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import nextWorker, {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "./.open-next/worker.js";
import { runRefreshCycle } from "./src/lib/refresh-service";
import type { RuntimeEnv } from "./src/lib/runtime-env";

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type ScheduledController = {
  cron: string;
  scheduledTime: number;
};

export { BucketCachePurge, DOQueueHandler, DOShardedTagCache };

const worker = {
  async fetch(request: Request, env: RuntimeEnv, ctx: WorkerContext) {
    return nextWorker.fetch(request, env, ctx);
  },
  async scheduled(controller: ScheduledController, env: RuntimeEnv, ctx: WorkerContext) {
    ctx.waitUntil(
      runRefreshCycle({
        env,
        source: `cron:${controller.cron}`,
        now: new Date(controller.scheduledTime),
      }),
    );
  },
};

export default worker;
